hazelcast/imdg-docs

.gitignore, docs/4.0/modules/ROOT/pages/index.adoc
=> Fix version 4.0

antora-playbook-local.yml, docs/modules/ROOT/pages/faq.adoc, docs/modules/ROOT/pages/getting-started.adoc, docs/modules/ROOT/pages/starting-members-clients.adoc, docs/modules/computing/pages/executor-service.adoc, docs/modules/data-structures/pages/map.adoc, docs/modules/data-structures/pages/multimap.adoc, docs/modules/data-structures/pages/pn-counter.adoc, docs/modules/data-structures/pages/reliable-topic.adoc, docs/modules/data-structures/pages/topic.adoc, docs/modules/integrated-clustering/pages/spring.adoc, docs/modules/management/pages/cluster-utilities.adoc, docs/modules/management/pages/management-center.adoc, docs/modules/performance/pages/slowoperationdetector.adoc, docs/modules/security/pages/tls-configuration.adoc, docs/modules/storage/pages/hot-restart-persistence.adoc, docs/modules/wan/pages/advanced-features.adoc, docs/modules/wan/pages/tuning.adoc
Updated links to the Management Center
=> Use internal references for MC docs

docs/modules/clients/pages/java.adoc, docs/modules/data-structures/pages/queue.adoc
Updated some references to `mc-docs` that were not updated in the previous commits
=> Fix broken attributes

docs/modules/cp-subsystem/pages/management.adoc
=> Fixing the name of CP subsystem script.

.github/workflows/build-site.yml, .github/workflows/build-staging.yml, .github/workflows/validate.yml, README.adoc, antora-playbook-local.yml
- Documented the release process
- Adjusted the GitHub Actions to trigger validation steps on pull requests to .z branches
=> Add release docs

README.adoc
Couple of adjustments in `Major and Minor Releases` + I unified versions in examples for `Patch Releases`. @Holmistr please review whether it's reflect conclusions from our meeting.
=> Adjust release doc

README.adoc
One more change - maintenance branch is created once the release branch is created. I moved steps 7. and 9. from Major and Minor Releases after step 4.
=> Update when .z branch is created

docs/modules/cp-subsystem/pages/cp-subsystem.adoc, docs/modules/data-structures/pages/map.adoc
Confusing content about the remove and delete operations on IMap, with a map store.
=> Fix for #74

docs/modules/security/pages/native-client-security.adoc
Fix copy paste errors in member config examples
=> Fix member config examples in native client security page

docs/modules/security/pages/native-client-security.adoc
Cover documentation for the hazelcast/hazelcast#18264 (not yet merged!)
=> Add management-permission description

docs/modules/ROOT/pages/migration-guides.adoc
Syncing with the related recent change on master.
=> Adding the GroupProperty entry to the Migration Guide.

docs/modules/ROOT/pages/phone-homes.adoc
Core PR: https://github.com/hazelcast/hazelcast/pull/18337
=> Add docs for classpath

docs/modules/data-structures/pages/map.adoc, docs/modules/query/pages/how-distributed-query-works.adoc
See also https://github.com/hazelcast/imdg-docs/commit/8177d1fc7440a9bcbc7651cb1f93a09b78eabae0 for the link to the SQL chapter.
Fixes: https://github.com/hazelcast/imdg-docs/issues/120
=> Fixes #120

docs/modules/management/pages/health-check-monitoring.adoc
Replaced left quotes with straight quotes in configuration example.
=> Fixed quote format problem

docs/modules/clients/pages/java.adoc
=> Fix typo in Java Client Smart Routing

docs/modules/clients/pages/java.adoc, docs/modules/sql/pages/querying-imap.adoc
Reverts hazelcast/imdg-docs#192
=> Revert "Doc fixes"

docs/modules/ROOT/pages/getting-started.adoc
=> Remove note about CLI not being production ready

docs/modules/clusters/pages/partition-group-configuration.adoc
related to https://github.com/hazelcast/hazelcast/pull/18780
=> Cleanup of deprecated Rack and Host metadata from Zone Aware group

docs/modules/data-structures/pages/creating-a-map.adoc
=> Update `Writing JSON to a Map` section

docs/modules/clients/pages/java.adoc
Related to https://github.com/hazelcast/hazelcast/pull/19219
=> Document deprecation of statistics property.

docs/modules/data-structures/pages/map.adoc
=> Fix eviction configuration for Map using HD Memory

docs/modules/data-structures/pages/map.adoc
Backport of #279 to 4.1 documentation.
=> [4.1][Backport] Fix eviction configuration for Map using HD Memory

docs/modules/ROOT/pages/getting-started.adoc
- Context and sample error handling mechanism were added. @yuce @utku-caglayan
=> Update obsolete go client IMDG `Quickstart` example

docs/modules/ROOT/pages/system-properties.adoc
During https://github.com/hazelcast/hazelcast/issues/20439 I found some inconsistencies between [docs](https://docs.hazelcast.com/imdg/4.2/system-properties) and actual source code default values
=> Actualized some system-properties default values

.gitignore, docs/antora.yml, docs/modules/ROOT/pages/migration-guides.adoc
```
1:46:08 AM: [22:46:08.375] WARN (asciidoctor): unterminated listing block
1:46:08 AM:     file: docs/modules/ROOT/pages/migration-guides.adoc:1375
1:46:08 AM:     source: https://github.com/hazelcast/imdg-docs (branch: v/4.0 | start path: docs)
1:46:08 AM: [22:46:08.377] WARN (asciidoctor): unterminated listing block
1:46:08 AM:     file: docs/modules/ROOT/pages/migration-guides.adoc:1393
1:46:08 AM:     source: https://github.com/hazelcast/imdg-docs (branch: v/4.0 | start path: docs)
1:46:08 AM: [22:46:08.377] ERROR (asciidoctor): dropping cells from incomplete row detected end of table
1:46:08 AM:     file: docs/modules/ROOT/pages/migration-guides.adoc:1393
1:46:08 AM:     source: https://github.com/hazelcast/imdg-docs (branch: v/4.0 | start path: docs)
1:46:08 AM: [22:46:08.538] …
```
=> Fix build errors v/4.0

.gitignore, docs/antora.yml, docs/modules/ROOT/pages/migration-guides.adoc
```
1:46:13 AM: [22:46:13.963] WARN (asciidoctor): unterminated listing block
1:46:13 AM:     file: docs/modules/ROOT/pages/migration-guides.adoc:1375
1:46:13 AM:     source: https://github.com/hazelcast/imdg-docs (branch: v/4.1 | start path: docs)
1:46:13 AM: [22:46:13.964] WARN (asciidoctor): unterminated listing block
1:46:13 AM:     file: docs/modules/ROOT/pages/migration-guides.adoc:1393
1:46:13 AM:     source: https://github.com/hazelcast/imdg-docs (branch: v/4.1 | start path: docs)
1:46:13 AM: [22:46:13.965] ERROR (asciidoctor): dropping cells from incomplete row detected end of table
1:46:13 AM:     file: docs/modules/ROOT/pages/migration-guides.adoc:1393
1:46:13 AM:     source: https://github.com/hazelcast/imdg-docs (branch: v/4.1 | start path: docs)
1:46:16 AM: [22:46:16.461] …
```
=> Fix build errors v/4.1

.gitignore, docs/modules/ROOT/pages/migration-guides.adoc
```
1:46:19 AM: [22:46:19.257] WARN (asciidoctor): unterminated listing block
1:46:19 AM:     file: docs/modules/ROOT/pages/migration-guides.adoc:1378
1:46:19 AM:     source: https://github.com/hazelcast/imdg-docs (branch: v/4.2 | start path: docs)
1:46:19 AM: [22:46:19.258] WARN (asciidoctor): unterminated listing block
1:46:19 AM:     file: docs/modules/ROOT/pages/migration-guides.adoc:1396
1:46:19 AM:     source: https://github.com/hazelcast/imdg-docs (branch: v/4.2 | start path: docs)
1:46:19 AM: [22:46:19.259] ERROR (asciidoctor): dropping cells from incomplete row detected end of table
1:46:19 AM:     file: docs/modules/ROOT/pages/migration-guides.adoc:1396
1:46:19 AM:     source: https://github.com/hazelcast/imdg-docs (branch: v/4.2 | start path: docs)
``` …
=> Fix build errors v/4.2
